sudo: required
services:
  - docker

before_install:
  - docker build -t tigranyengiba04/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tigranyengiba04/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-220423856836"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


#  %*AGtZF3I!e$[{G
